version: '3.9'
services:
  mysql:
    hostname: mysql
    image: 'mysql:latest'
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: project
  project:
    image: 'project'
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/backend
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - mysql